-- Create Books Table
create table if not exists public.books (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  title text not null,
  type text not null,
  file_path text not null, -- Path in Storage Bucket
  progress text, -- Page number or CFI
  total_pages integer,
  last_read timestamptz default now(),
  updated_at timestamptz default now(),
  deleted boolean default false,
  created_at timestamptz default now()
);

alter table public.books enable row level security;

create policy "Users can view their own books" on public.books
  for select using (auth.uid() = user_id);

create policy "Users can insert their own books" on public.books
  for insert with check (auth.uid() = user_id);

create policy "Users can update their own books" on public.books
  for update using (auth.uid() = user_id);

create policy "Users can delete their own books" on public.books
  for delete using (auth.uid() = user_id);

-- Create Vocabulary Table
create table if not exists public.vocabulary (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  word text not null,
  part_of_speech text,
  definition text, -- JSON string or simple text
  meanings jsonb, -- Store complex meanings structure
  fsrs jsonb, -- Store SRS data (stability, difficulty, etc.)
  updated_at timestamptz default now(),
  deleted boolean default false,
  date_added timestamptz default now()
);

alter table public.vocabulary enable row level security;

create policy "Users can view their own vocabulary" on public.vocabulary
  for select using (auth.uid() = user_id);

create policy "Users can insert their own vocabulary" on public.vocabulary
  for insert with check (auth.uid() = user_id);

create policy "Users can update their own vocabulary" on public.vocabulary
  for update using (auth.uid() = user_id);

create policy "Users can delete their own vocabulary" on public.vocabulary
  for delete using (auth.uid() = user_id);

-- Create Reading Sessions Table
create table if not exists public.reading_sessions (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  book_id bigint references public.books(id) on delete cascade,
  page text not null,
  duration integer not null, -- Seconds or Milliseconds
  start_time timestamptz not null,
  end_time timestamptz not null,
  date date not null -- For easy grouping
);

alter table public.reading_sessions enable row level security;

create policy "Users can view their own sessions" on public.reading_sessions
  for select using (auth.uid() = user_id);

create policy "Users can insert their own sessions" on public.reading_sessions
  for insert with check (auth.uid() = user_id);

-- Storage Bucket for Book Files
insert into storage.buckets (id, name)
values ('book-files', 'book-files')
on conflict (id) do nothing;

create policy "Users can upload their own book files" on storage.objects
  for insert with check (bucket_id = 'book-files' and auth.uid() = owner);

create policy "Users can view their own book files" on storage.objects
  for select using (bucket_id = 'book-files' and auth.uid() = owner);
